2023-01-22 10:20:50,672 ERROR Internal Server Error: /news/ /home/maks/PycharmProjects/skilfactory_django/venv/lib/python3.10/site-packages/django/utils/log.py (<class 'django.db.utils.OperationalError'>, OperationalError('no such column: D5_post.title_en'), <traceback object at 0x7f191593cc80>)
Traceback (most recent call last):
  File "/home/maks/PycharmProjects/skilfactory_django/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/home/maks/PycharmProjects/skilfactory_django/venv/lib/python3.10/site-packages/django/db/backends/sqlite3/base.py", line 357, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such column: D5_post.title_en

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/maks/PycharmProjects/skilfactory_django/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/maks/PycharmProjects/skilfactory_django/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/home/maks/PycharmProjects/skilfactory_django/venv/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/home/maks/PycharmProjects/skilfactory_django/venv/lib/python3.10/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "/home/maks/PycharmProjects/skilfactory_django/venv/lib/python3.10/site-packages/django/template/backends/django.py", line 62, in render
    return self.template.render(context)
  File "/home/maks/PycharmProjects/skilfactory_django/venv/lib/python3.10/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/home/maks/PycharmProjects/skilfactory_django/venv/lib/python3.10/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/maks/PycharmProjects/skilfactory_django/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/maks/PycharmProjects/skilfactory_django/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/maks/PycharmProjects/skilfactory_django/venv/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/maks/PycharmProjects/skilfactory_django/venv/lib/python3.10/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "/home/maks/PycharmProjects/skilfactory_django/venv/lib/python3.10/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/maks/PycharmProjects/skilfactory_django/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/maks/PycharmProjects/skilfactory_django/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/maks/PycharmProjects/skilfactory_django/venv/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/maks/PycharmProjects/skilfactory_django/venv/lib/python3.10/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "/home/maks/PycharmProjects/skilfactory_django/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/maks/PycharmProjects/skilfactory_django/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/maks/PycharmProjects/skilfactory_django/venv/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/maks/PycharmProjects/skilfactory_django/venv/lib/python3.10/site-packages/django/template/defaulttags.py", line 321, in render
    if match:
  File "/home/maks/PycharmProjects/skilfactory_django/venv/lib/python3.10/site-packages/django/db/models/query.py", line 408, in __bool__
    self._fetch_all()
  File "/home/maks/PycharmProjects/skilfactory_django/venv/lib/python3.10/site-packages/django/db/models/query.py", line 1866, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/maks/PycharmProjects/skilfactory_django/venv/lib/python3.10/site-packages/django/db/models/query.py", line 87, in __iter__
    results = compiler.execute_sql(
  File "/home/maks/PycharmProjects/skilfactory_django/venv/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1398, in execute_sql
    cursor.execute(sql, params)
  File "/home/maks/PycharmProjects/skilfactory_django/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 103, in execute
    return super().execute(sql, params)
  File "/home/maks/PycharmProjects/skilfactory_django/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/home/maks/PycharmProjects/skilfactory_django/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/maks/PycharmProjects/skilfactory_django/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/home/maks/PycharmProjects/skilfactory_django/venv/lib/python3.10/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/maks/PycharmProjects/skilfactory_django/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/home/maks/PycharmProjects/skilfactory_django/venv/lib/python3.10/site-packages/django/db/backends/sqlite3/base.py", line 357, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such column: D5_post.title_en
2023-01-22 10:20:50,673 ERROR "GET /news/ HTTP/1.1" 500 216953 /home/maks/PycharmProjects/skilfactory_django/venv/lib/python3.10/site-packages/django/core/servers/basehttp.py None
2023-01-22 11:07:20,321 ERROR Internal Server Error: /news/ /home/maks/PycharmProjects/skilfactory_django/venv/lib/python3.10/site-packages/django/utils/log.py (<class 'django.db.utils.OperationalError'>, OperationalError('no such column: D5_category.name_category_en'), <traceback object at 0x7f99bed8a840>)
Traceback (most recent call last):
  File "/home/maks/PycharmProjects/skilfactory_django/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/home/maks/PycharmProjects/skilfactory_django/venv/lib/python3.10/site-packages/django/db/backends/sqlite3/base.py", line 357, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such column: D5_category.name_category_en

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/maks/PycharmProjects/skilfactory_django/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/maks/PycharmProjects/skilfactory_django/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/home/maks/PycharmProjects/skilfactory_django/venv/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/home/maks/PycharmProjects/skilfactory_django/venv/lib/python3.10/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "/home/maks/PycharmProjects/skilfactory_django/venv/lib/python3.10/site-packages/django/template/backends/django.py", line 62, in render
    return self.template.render(context)
  File "/home/maks/PycharmProjects/skilfactory_django/venv/lib/python3.10/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/home/maks/PycharmProjects/skilfactory_django/venv/lib/python3.10/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/maks/PycharmProjects/skilfactory_django/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/maks/PycharmProjects/skilfactory_django/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/maks/PycharmProjects/skilfactory_django/venv/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/maks/PycharmProjects/skilfactory_django/venv/lib/python3.10/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "/home/maks/PycharmProjects/skilfactory_django/venv/lib/python3.10/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/maks/PycharmProjects/skilfactory_django/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/maks/PycharmProjects/skilfactory_django/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/maks/PycharmProjects/skilfactory_django/venv/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/maks/PycharmProjects/skilfactory_django/venv/lib/python3.10/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "/home/maks/PycharmProjects/skilfactory_django/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/maks/PycharmProjects/skilfactory_django/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/maks/PycharmProjects/skilfactory_django/venv/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/maks/PycharmProjects/skilfactory_django/venv/lib/python3.10/site-packages/django/template/defaulttags.py", line 322, in render
    return nodelist.render(context)
  File "/home/maks/PycharmProjects/skilfactory_django/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/maks/PycharmProjects/skilfactory_django/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/maks/PycharmProjects/skilfactory_django/venv/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/maks/PycharmProjects/skilfactory_django/venv/lib/python3.10/site-packages/django/template/defaulttags.py", line 238, in render
    nodelist.append(node.render_annotated(context))
  File "/home/maks/PycharmProjects/skilfactory_django/venv/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/maks/PycharmProjects/skilfactory_django/venv/lib/python3.10/site-packages/django/template/defaulttags.py", line 194, in render
    len_values = len(values)
  File "/home/maks/PycharmProjects/skilfactory_django/venv/lib/python3.10/site-packages/django/db/models/query.py", line 376, in __len__
    self._fetch_all()
  File "/home/maks/PycharmProjects/skilfactory_django/venv/lib/python3.10/site-packages/django/db/models/query.py", line 1866, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/maks/PycharmProjects/skilfactory_django/venv/lib/python3.10/site-packages/django/db/models/query.py", line 87, in __iter__
    results = compiler.execute_sql(
  File "/home/maks/PycharmProjects/skilfactory_django/venv/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1398, in execute_sql
    cursor.execute(sql, params)
  File "/home/maks/PycharmProjects/skilfactory_django/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 103, in execute
    return super().execute(sql, params)
  File "/home/maks/PycharmProjects/skilfactory_django/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/home/maks/PycharmProjects/skilfactory_django/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/maks/PycharmProjects/skilfactory_django/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/home/maks/PycharmProjects/skilfactory_django/venv/lib/python3.10/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/maks/PycharmProjects/skilfactory_django/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/home/maks/PycharmProjects/skilfactory_django/venv/lib/python3.10/site-packages/django/db/backends/sqlite3/base.py", line 357, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such column: D5_category.name_category_en
2023-01-22 11:07:20,322 ERROR "GET /news/ HTTP/1.1" 500 270534 /home/maks/PycharmProjects/skilfactory_django/venv/lib/python3.10/site-packages/django/core/servers/basehttp.py None
